### ISSUE TITLE
npm run dev 报错是怎么回事？？？

### ISSUE THREAD

**Issue by ysxhd** [jas0ncn/resume#1]
node_modules也都下载下来了，这是提示我？？？
![11111](https://cloud.githubusercontent.com/assets/11511828/24655343/74048d0a-1970-11e7-94b1-a8d111796362.jpeg)

**Comment by jas0ncn** [comment]
这是你的 8080 已经被占用了，你可以查找一下被哪个程序占用了，关掉即可。

**Comment by ysxhd** [comment]
再问一下啊，为什么你的vue脚手架没有webpack.config.js，我想添加一个css-loader，不知道往哪添加额。。。
